# Generated by Django 5.0.3 on 2024-03-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=256, verbose_name='Название поста')),
                ('post_description', models.TextField(verbose_name='Статья')),
                ('post_author', models.CharField(help_text='ФИО автора', max_length=64, verbose_name='Автор статьи')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('text_comments', models.TextField(max_length=2000, verbose_name='Коментарий')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.postmodel', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.CreateModel(
            name='ProcedureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_title', models.CharField(max_length=128, verbose_name='Название процедуры')),
                ('procedure_description', models.TextField(verbose_name='Описание процедуры')),
                ('procedure_price', models.FloatField(verbose_name='Цена процедуры')),
                ('procedure_image', models.FileField(upload_to='procedure_image', verbose_name='Файл(Фото) процедуры')),
                ('procedure_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания процедуры')),
                ('procedure_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.categorymodel', verbose_name='Категория процедуры')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='id пользователя')),
                ('user_add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedures.proceduremodel', verbose_name='Выбранная процедура')),
            ],
            options={
                'verbose_name': 'Запись на процедуру',
                'verbose_name_plural': 'Запись на процедуры',
            },
        ),
    ]
